apiVersion: 1

contactPoints:
  - orgId: 1
    name: matrix-webhook
    receivers:
      - uid: matrix-webhook-01
        type: webhook
        settings:
          url: "${MATRIX_WEBHOOK_URL}"
          httpMethod: POST
          title: "{{ .GroupLabels.alertname }}"
          message: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        disableResolveMessage: false
